version: '3'

networks:
  inception:
    name: inception

volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: ~/data/mariadb_data
      o: bind
  wordpress_data:
    driver_opts:
      type: none
      device: "~/data/wordpress_data"
      o: bind

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    image: nginx:stelie42
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    image: mariadb:stelie42
    expose:
      - "3306"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
