version: '3'

networks:
  inception:
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/stelie/data/mysql
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:stelie42
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mysql:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:stelie42
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
