version: '3'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: ~/data/db_data
      type: none
      o: bind
  wordpress_data:
    driver: local    
    driver_opts:
      device: ~/data/wp_data
      type: none
      o: bind

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:stelie42
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/stelie.42.fr
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:stelie42
    expose:
      - "3306"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:stelie42
    expose:
      - "9000"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/stelie.42.fr
    depends_on:
      - mariadb
    restart: always
