version: '3'

networks:
  inception:
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/stelie/data/mysql
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb:MDB
    expose:
      - 3306
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure

  db:
    container_name: db
    build: ./db
    image: db:MDB
    expose:
      - 3306
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure 


    